version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: cd.go.plugin:go-plugin-api
    versions:
    - 20.9.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - 4.9.0
